# Generated by Django 4.2 on 2023-04-29 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=300)),
                ("envent_image", models.ImageField(upload_to="event")),
                ("tagline", models.CharField(max_length=500)),
                ("schedule", models.DateTimeField()),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=200)),
                ("sub_category", models.CharField(max_length=200)),
                ("attendees", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
