# Generated by Django 4.2 on 2023-04-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="envent_image",
            field=models.ImageField(null=True, upload_to="event"),
        ),
    ]
